version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: weekly
    day: tuesday
    time: '09:00'
  open-pull-requests-limit: 10
  reviewers:
    - themakunga
  assignees:
    - themakunga
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: weekly
    day: wednesday
    time: '10:00'
  open-pull-requests-limit: 10
  reviewers:
    - themakunga
  assignees:
    - themakunga
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
