env:
  commonjs: true
  browser: false
  es6: true
  node: true
  mocha: true
extends:
  - airbnb-base
  - plugin:json/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
rules: {}
