env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
rules:
  import/prefer-default-export: 0
  import/extensions:
    - error
    - ignorePackages
    - js: never
      ts: never
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: ./tsconfig.json
    node:
      extensions:
        - .js
        - .ts
