name: npm-publish
on:
  pull_request:
    branches:
      - main
jobs:
  release:
    if: github.event_name == 'push' && github.ref == 'refs/head/main'
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install
        run: npm ci
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
